apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: bookstore
type: Opaque
stringData:
  secret-key: "bookstore-k8s-secret-change-me"

  mongodb-root-username: "admin"

  mongodb-root-password: "BookstoreMongo_2026_Strong!"

  mongodb-url: "mongodb://admin:BookstoreMongo_2026_Strong!@mongodb:27017/bookstore?authSource=admin"

  admin-password: "BookstoreAdmin_2026_Strong!"